# This is a sample github action to build and release your plugin using a github action
# It will run when pushing a new tag - the tag name must be your plugin version number (e.g. "1.0.0.0")
# Replace and adjust the areas that are commented below
# Place it into the workflow folder of your repository at .github/workflows

# The action can also automatically publish your manifest
# Fork the manifest repo from here https://github.com/isbeorn/nina.plugin.manifests and also name it "nina.plugin.manifests"
# Additionally create a personal access token with write permissions to this fork and add it to your plugin repository secrets with key name "PAT"
name: Build and Release

# Every time a new tag with the typical assembly format is pushed this will run. e.g. tag name "1.0.0.0"
on:
  push:
    tags:
      - 'exp-[0-9]+.[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

env:
  # Adjust this to your plugin title
  PLUGIN_NAME: "NikonEkrynoxSdk"
  # Your solution name
  PLUGIN_SLN_NAME: "Nikon Ekrynox SDK for NINA"
  # The name of the resulting dll file
  PLUGIN_DLL_NAME: "LucasAlias.NINA.NikonEkrynoxSdk"
  # The relative path to your manifest folder inside the manifest repository
  PLUGIN_MANIFEST_PATH: "n/NikonEkrynoxSdk"
  # Compilation parameters
  BUILD_CONFIGURATION: Release
  PLATFORM: x64

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install NuGet CLI
        run: choco install nuget.commandline --yes
        
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        run: nuget restore "${{ env.PLUGIN_SLN_NAME }}.sln"
        
      - name: Restore packages via MSBuild (just in case NuGet missed some SDK-style stuff)
        run: msbuild "${{ env.PLUGIN_SLN_NAME }}.sln" /t:Restore /p:Platform=${{env.PLATFORM}} /p:Configuration=${{env.BUILD_CONFIGURATION}}

      # In case you need more sub folders add these here
      - name: Prepare folders
        run: |
          mkdir packages
          mkdir "packages/${{ env.PLUGIN_NAME }}"
          mkdir "packages/${{ env.PLUGIN_NAME }}/runtimes/"
          mkdir "packages/${{ env.PLUGIN_NAME }}/runtimes/win-${{env.PLATFORM}}"
          mkdir "packages/${{ env.PLUGIN_NAME }}/runtimes/win-${{env.PLATFORM}}/native"

      - name: Build .NET Assemblies
        run: msbuild /m /p:Platform=${{env.PLATFORM}} /p:Configuration=${{env.BUILD_CONFIGURATION}} "${{env.PLUGIN_SLN_NAME}}.sln" -p:PostBuildEvent= -p:Version=${{ github.ref_name }} -p:OutputPath="./bin/${{ env.BUILD_CONFIGURATION }}"


      # Add all necessary files that the plugin needs to the packages folder - basically all items that are normally in your post build event on your local builds
      - name: Prepare package
        run: |
          Copy-Item "bin/${{ env.BUILD_CONFIGURATION }}/${{ env.PLUGIN_DLL_NAME }}.dll" "packages/${{ env.PLUGIN_NAME }}/${{ env.PLUGIN_DLL_NAME }}.dll" -Force
          Copy-Item "bin/${{ env.BUILD_CONFIGURATION }}/${{ env.PLUGIN_DLL_NAME }}.pdb" "packages/${{ env.PLUGIN_NAME }}/${{ env.PLUGIN_DLL_NAME }}.pdb" -Force       
          Copy-Item "${{env.PLATFORM}}/${{ env.BUILD_CONFIGURATION }}/Ijwhost.dll" "packages/${{ env.PLUGIN_NAME }}/runtimes/win-${{env.PLATFORM}}/native/Ijwhost.dll" -Force
          Copy-Item "${{env.PLATFORM}}/${{ env.BUILD_CONFIGURATION }}/NEKCS.Wrapper.dll" "packages/${{ env.PLUGIN_NAME }}/runtimes/win-${{env.PLATFORM}}/native/NEKCS.Wrapper.dll" -Force
          Copy-Item "${{env.PLATFORM}}/${{ env.BUILD_CONFIGURATION }}/NEKCS.Wrapper.pdb" "packages/${{ env.PLUGIN_NAME }}/runtimes/win-${{env.PLATFORM}}/native/NEKCS.Wrapper.pdb" -Force
          Copy-Item "${{env.PLATFORM}}/${{ env.BUILD_CONFIGURATION }}/NEK.dll" "packages/${{ env.PLUGIN_NAME }}/runtimes/win-${{env.PLATFORM}}/native/NEK.dll" -Force
          Copy-Item "${{env.PLATFORM}}/${{ env.BUILD_CONFIGURATION }}/NEK.pdb" "packages/${{ env.PLUGIN_NAME }}/runtimes/win-${{env.PLATFORM}}/native/NEK.pdb" -Force
          
          Copy-Item "bin/${{ env.BUILD_CONFIGURATION }}/Database" "packages/${{ env.PLUGIN_NAME }}/" -Recurse -Force
          
      - name: Create Plugin archives and manifests
        run: |
          curl -LO https://raw.githubusercontent.com/isbeorn/nina.plugin.manifests/refs/heads/main/tools/CreateManifest.ps1?raw=true
          pwsh CreateManifest.ps1 -file "packages/${{ env.PLUGIN_NAME }}/${{ env.PLUGIN_DLL_NAME }}.dll" -installerUrl "https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/${{ env.PLUGIN_DLL_NAME }}.${{ github.ref_name }}.zip" -createArchive -includeAll -beta
          Rename-Item -Path "manifest.json" -NewName "${{ env.PLUGIN_DLL_NAME }}.${{ github.ref_name }}.manifest.json"
          Rename-Item -Path ${{ env.PLUGIN_DLL_NAME }}.zip -NewName ${{ env.PLUGIN_DLL_NAME }}.${{ github.ref_name }}.zip

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: Experimental ${{ github.ref_name }}
          draft: false
          prerelease: true
          files: |
            ./${{ env.PLUGIN_DLL_NAME }}.${{ github.ref_name }}.zip
            ./${{ env.PLUGIN_DLL_NAME }}.${{ github.ref_name }}.manifest.json
      
      - name: Upload manifest artifact
        uses: actions/upload-artifact@v4
        with:
          name: plugin-manifest
          path: ${{ env.PLUGIN_DLL_NAME }}.${{ github.ref_name }}.manifest.json